apiVersion: apps/v1
kind: Deployment
metadata:
  name: square-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: square-app
  template:
    metadata:
      labels:
        app: square-app
    spec:
      containers:
      - name: square-app
        image: aschiebold/square-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=square-app,service.namespace=square-ns,deployment.environment=dev"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://otlp-gateway-prod-us-east-2.grafana.net/otlp"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: Authorization=Basic%20MTI1NDg4NjpnbGNfZXlKdklqb2lNVFF5TnpNek1DSXNJbTRpT2lKemRHRmpheTB4TWpVME9EZzJMVzkwWld3dGIyNWliMkZ5WkdsdVp5MWhiR3hoYmlJc0ltc2lPaUkxY25VeVZqUXliWG8xY0habmNIb3hUVEZ2YlRsMk9URWlMQ0p0SWpwN0luSWlPaUp3Y205a0xYVnpMV1ZoYzNRdE1DSjlmUT09
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"