apiVersion: apps/v1
kind: Deployment
metadata:
  name: square-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: square-app
  template:
    metadata:
      labels:
        app: square-app
    spec:
      containers:
      - name: square-app
        image: aschiebold/square-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://otlp.grafana.net:443"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          valueFrom:
            secretKeyRef:
              name: grafana-cloud-secret
              key: grafana-auth-header
        - name: OTEL_SERVICE_NAME
          value: "square-app"