name: Deploy Kubernetes Manifests
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Kind
        uses: helm/kind-action@v1.8.0
        with:
          clusterName: test-cluster
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Verify cluster
        run: |
          kubectl cluster-info
          kubectl get nodes
      - name: Create secret.yaml
        run: echo "${{ secrets.SECRET_YAML }}" > kubernetes/secret.yaml
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/secret.yaml -f kubernetes/deployment.yaml -f kubernetes/service.yaml --validate=false
