name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to latest version
      - name: Set up Python
        uses: actions/setup-python@v5 # Updated to latest version
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: python -m unittest discover tests

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to latest version
      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Updated to latest version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6 # Updated to latest version
        with:
          context: .
          push: true
          tags: aschiebold/square-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to latest version
      - name: Set up Kind
        uses: helm/kind-action@v1.10.0 # Latest version
        with:
          clusterName: test-cluster
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4 # Updated to latest version
      - name: Verify cluster
        run: |
          kubectl cluster-info
          kubectl get nodes
      - name: Create secret.yaml (if needed)
        if: env.SECRET_YAML != '' # Only run if SECRET_YAML secret exists
        run: echo "${{ secrets.SECRET_YAML }}" > kubernetes/secret.yaml
        env:
          SECRET_YAML: ${{ secrets.SECRET_YAML }}
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/secret.yaml -f kubernetes/deployment.yaml -f kubernetes/service.yaml --validate=false
